apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 357806352922.dkr.ecr.ap-northeast-2.amazonaws.com/moine_auth:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: auth_database_url
            - name: DATABASE_USERID
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: database_userid
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: database_password
#            - name: KAFKA_ENDPOINT
#              valueFrom:
#                configMapKeyRef:
#                  name: moine-backend-configmap
#                  key: kafka_endpoint
#          readinessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 10
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 10
#          livenessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 120
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 5